Overdue checkin ;-)

diff --git a/slackrepo b/slackrepo
--- a/slackrepo
+++ b/slackrepo
@@ -27,11 +27,15 @@
 function print_usage
 {
   echo 'Usage:'
-  echo '  slackrepo add     [--repo=ID] [item...]'
-  echo '  slackrepo rebuild [--repo=ID] [item...]'
-  echo '  slackrepo remove  [--repo=ID] item...'
-  echo '  slackrepo update  [--repo=ID] [--dry-run ] [item...]'
-  echo '  slackrepo update  [--repo=ID] --apply[=file]'
+  echo '  slackrepo build   [--control_args] [item...]'
+  echo '  slackrepo rebuild [--control_args] [item...]'
+  echo '  slackrepo update  [--control_args] [item...]'
+  echo '  slackrepo remove  [--control_args] item...'
+  echo 'Control args:'
+  echo '  --repo=ID'
+  echo '  --test'
+  echo '  --dry-run'
+  echo '  --verbose | --quiet'
   return
 }
 
@@ -46,16 +50,15 @@ starttime=$(date +%s)
 PROCMODE=''
 OPT_TEST='n'
 OPT_DRYRUN='n'
-OPT_APPLY='n'
 OPT_VERBOSE='n'
 OPT_QUIET='n'
 
 while [ $# != 0 ]; do
   case "$1" in
-    # we'll accept add/rebuild/update/remove with or without '--'
-    add | --add )
+    # we'll accept build/rebuild/update/remove with or without '--'
+    build | --build )
       [ -n "$PROCMODE" ] && { print_usage; exit 3; }
-      PROCMODE='add'
+      PROCMODE='build'
       shift; continue ;;
     rebuild | --rebuild )
       [ -n "$PROCMODE" ] && { print_usage; exit 3; }
@@ -82,21 +85,7 @@ while [ $# != 0 ]; do
       OPT_TEST='y'
       shift; continue ;;
     --dry-run )
-      # --dry-run is incompatible with --apply
-      [ "$OPT_APPLY" = 'y' ] && { print_usage; exit 3; }
       OPT_DRYRUN='y'
-      shift; continue ;;
-    --apply=* )
-      # --apply is incompatible with --dry-run
-      [ "$OPT_DRYRUN" = 'y' ] && { print_usage; exit 3; }
-      OPT_APPLY='y'
-      SR_UPDATEFILE="$(echo "$1" | sed 's/^--apply=//')"
-      shift; continue ;;
-    --apply )
-      # --apply is incompatible with --dry-run
-      [ "$OPT_DRYRUN" = 'y' ] && { print_usage; exit 3; }
-      OPT_APPLY='y'
-      SR_UPDATEFILE=""  # fill this in later when we've read the config
       shift; continue ;;
     --* )
       print_usage; exit 3 ;;
@@ -107,15 +96,13 @@ done
 
 [ -z "$PROCMODE" ] && \
   { print_usage; exit 3; }
-[ "$OPT_APPLY" = 'y' -a "$PROCMODE" != 'update' ] && \
-  { print_usage; exit 3; }
 
 #-------------------------------------------------------------------------------
 # Startup
 #-------------------------------------------------------------------------------
 
-# Ensure ctrl-c exits the whole thing, not just a random subshell
-trap "exit 2" SIGINT SIGQUIT SIGTERM
+# Ensure ctrl-c (etc) exits the whole thing, not just a random subshell
+trap "exit 1" SIGINT SIGQUIT SIGTERM
 
 # Get the support functions
 for f in /usr/libexec/slackrepo/functions.d/*functions.sh; do
@@ -128,29 +115,34 @@ done
 # Configuration
 #-------------------------------------------------------------------------------
 
-# Set the repo ID: from control arg, or env...
+# This is for things that SR_TMP wouldn't be good for
+# (SR_TMP gets cleaned during execution)
+TMPDIR=${TMPDIR:-/tmp}
+
+# Set the repo ID from control arg, or env...
 SR_REPO="${SR_REPO:-$REPO}"
-# ... or repo.default config file ...
-repodefault="/etc/slackrepo/repo.default"
-[ -f $repodefault ] && { set -e; . $repodefault; set +e; }
-# ... or just fall back to SBo.
+# ... or just fall back to hardcoded SBo.
 [ -z "${SR_REPO:=$REPO}" ] && SR_REPO="SBo"
 
 # Set config variables from environment:
-varlist="GITREPO BRANCH UPSTREAM STYLE SRCREPO PKGREPO TAG \
-         HINTS LOGDIR TMP ARCH PKGTYPE NUMJOBS USE_GENREPOS"
+varlist="SBREPO PKGREPO SRCREPO \
+         HINTS LOGDIR TMP \
+         ARCH TAG PKGTYPE NUMJOBS USE_GENREPOS"
 # We'll prefix all these with SR_ to stop SlackBuilds picking them up
 for envvar in $varlist ; do
   myvar="SR_$envvar"
   eval $myvar="${!envvar}"
 done
 # Read the config files:
-repoconf="/etc/slackrepo/repo_${SR_REPO}.conf"
-##### and ~/.slackrepo
+repoconf="/etc/slackrepo/slackrepo_${SR_REPO}.conf"
 if [ -f "$repoconf" ]; then
-  set -e; . "$repoconf"; set +e
+  . "$repoconf"
 else
   echo "Error: repo configuration file not found: $repoconf"; exit 2
+fi
+userconf="~/.slackreporc"
+if [ -f "$userconf" ]; then
+  . "$userconf"
 fi
 # Backfill the SR_ variables from config and unset the config variables
 for confvar in $varlist ; do
@@ -158,9 +150,6 @@ for confvar in $varlist ; do
   [ -z "${!myvar}" ] && eval $myvar="${!confvar}"
   eval unset $confvar
 done
-
-# This is for things that SR_TMP wouldn't be good for (we clean SR_TMP)
-TMPDIR=${TMPDIR:-/tmp}
 
 # Do this now so we can log the config:
 mkdir -p $SR_LOGDIR
@@ -183,28 +172,25 @@ if [ -z "$SR_BRANCH" ]; then
   SR_BRANCH="$SLACKVER"
 fi
 
-# For update mode:
-[ -z "$SR_UPDATEFILE" ] && SR_UPDATEFILE="$SR_LOGDIR/slackrepo_dryrun.log"
-
+# Log the config
 [ "$OPT_VERBOSE" = 'y' ] && echo ""
 log_verbose "Configuration:"
 [ "$OPT_VERBOSE" = 'y' ] && log_verbose "  --verbose"
 [ "$OPT_QUIET" = 'y'   ] && log_verbose "  --quiet"
 log_verbose "  --repo=$SR_REPO"
 log_verbose "  --$PROCMODE"
-[ "$OPT_DRYRUN" = 'y' ] && log_verbose "  --dry-run"
-[ "$OPT_APPLY"  = 'y' ] && log_verbose "  --apply=$SR_UPDATEFILE"
+[ "$OPT_DRYRUN" = 'y'  ] && log_verbose "  --dry-run"
 for var in $varlist; do
   myvar="SR_$var"
   log_verbose "  $var='${!myvar}'"
 done
 [ "$OPT_VERBOSE" = 'y' ] && echo ""
 
-[ -d "$SR_GITREPO" ] || { log_normal "$(basename $0): Creating git repository: $SR_GITREPO"     ; mkdir -p "$SR_GITREPO" ; }
-[ -d "$SR_SRCREPO" ] || { log_normal "$(basename $0): Creating source repository: $SR_SRCREPO"  ; mkdir -p "$SR_SRCREPO" ; }
-[ -d "$SR_PKGREPO" ] || { log_normal "$(basename $0): Creating package repository: $SR_PKGREPO" ; mkdir -p "$SR_PKGREPO" ; }
-[ -d "$SR_LOGDIR" ]  || { log_normal "$(basename $0): Creating log directory: $SR_LOGDIR"       ; mkdir -p "$SR_LOGDIR"  ; }
-[ -d "$SR_HINTS" ]   || { log_normal "$(basename $0): Creating hints directory: $SR_HINTS"      ; mkdir -p "$SR_HINTS"   ; }
+[ -d "$SR_SBREPO" ]  || { log_normal "$(basename $0): Creating SlackBuild repository: $SR_SBREPO" ; mkdir -p "$SR_SBREPO"  ; }
+[ -d "$SR_SRCREPO" ] || { log_normal "$(basename $0): Creating source repository: $SR_SRCREPO"    ; mkdir -p "$SR_SRCREPO" ; }
+[ -d "$SR_PKGREPO" ] || { log_normal "$(basename $0): Creating package repository: $SR_PKGREPO"   ; mkdir -p "$SR_PKGREPO" ; }
+[ -d "$SR_LOGDIR" ]  || { log_normal "$(basename $0): Creating log directory: $SR_LOGDIR"         ; mkdir -p "$SR_LOGDIR"  ; }
+[ -d "$SR_HINTS" ]   || { log_normal "$(basename $0): Creating hints directory: $SR_HINTS"        ; mkdir -p "$SR_HINTS"   ; }
 
 #-------------------------------------------------------------------------------
 # Initialisation
@@ -214,6 +200,10 @@ done
 declare -A INFOVERSION INFOREQUIRES INFODOWNLIST INFOMD5LIST
 # and to store dependency, revision and other stuff:
 declare -A SRCDIR GITREV GITDIRTY DEPCACHE REVCACHE
+# and for each type of hint:
+declare -A HINT_skipme HINT_md5ignore HINT_makej1 HINT_no_uninstall
+declare -A HINT_cleanup HINT_uidgid HINT_answers
+declare -A HINT_options HINT_optdeps HINT_readmedeps HINT_version
 
 # How clean is the system?
 if [ -n "$SR_TAG" ]; then
@@ -242,27 +232,22 @@ SR_CHANGELOG=$TMPDIR/sr_changelog.tmp
 # run, and gen_repos_files.sh can catch up with them at the end.
 touch $SR_CHANGELOG
 
-if [ "$OPT_DRYRUN" = 'y' -a "$PROCMODE" = "update" ]; then
-  >$SR_UPDATEFILE
-fi
-
 log_normal "Initialising git ..."
-if [ -d $SR_GITREPO/.git ]; then
-  cd $SR_GITREPO
+if [ -d $SR_SBREPO/.git ]; then
+  cd $SR_SBREPO
   ###### This bit needs a redo
-  ###### don't update if OPT_APPLY is happening
   ###### git checkout -f $SR_BRANCH
   if [ -n "$SR_UPSTREAM" -a "$SR_BRANCH" = "$SLACKVER" ]; then
-    if [ -n "$(find $SR_GITREPO/.git/FETCH_HEAD -mtime +1 2>/dev/null)" ]; then
+    if [ -n "$(find $SR_SBREPO/.git/FETCH_HEAD -mtime +1 2>/dev/null)" ]; then
       git fetch -a
       git merge --ff-only origin/$SR_BRANCH
     fi
   fi
 else
-  mkdir -p $SR_GITREPO
-  log_normal "Git repository $SR_GITREPO does not exist; creating it..."
-  git clone "$SR_UPSTREAM" "$SR_GITREPO"
-  cd "$SR_GITREPO"
+  mkdir -p $SR_SBREPO
+  log_normal "Git repository $SR_SBREPO does not exist; creating it..."
+  git clone "$SR_UPSTREAM" "$SR_SBREPO"
+  cd "$SR_SBREPO"
   git fetch -a
   git remote update
   git checkout -b "$SR_BRANCH" -t origin/"$SR_BRANCH"
@@ -278,29 +263,24 @@ SKIPPEDLIST=''
 FAILEDLIST=''
 ABORTEDLIST=''
 
-if [ "$PROCMODE" = 'update' ]; then
-  if [ "$OPT_APPLY" = 'y' ]; then
-    # update apply => throw away all the args, get the stored arg list
-    set -- $(cat "$SR_UPDATEFILE" | cut -f1 -d' ')
-  elif [ $# = 0 ]; then
-    # update mode with no args => process everything in the package repo
-    set -- $(cd $SR_PKGREPO; find * -maxdepth 0 -type d 2>/dev/null)
-  fi
-elif [ $# = 0 ]; then
+if [ $# = 0 ]; then
   if [ "$PROCMODE" = 'remove' ]; then
     # remove mode with no args => do nothing
     echo "Usage: slackrepo remove [--repo=ID] item..."
     echo "In remove mode, you *must* specify the items to be removed."
     exit 3
+  elif [ "$PROCMODE" = 'update' ]; then
+    # update mode with no args => process everything in the package repo
+    set -- $(cd $SR_PKGREPO; find * -maxdepth 0 -type d 2>/dev/null)
   else
     # other modes with no args => process everything in the git repo
-    set -- $(cd $SR_GITREPO; find * -maxdepth 0 -type d 2>/dev/null)
+    set -- $(cd $SR_SBREPO; find * -maxdepth 0 -type d 2>/dev/null)
   fi
 fi
 
 log_normal "Preparing list of items..."
 BLAME="$(basename $0)"
-if [ "$PROCMODE" = 'add' -o "$PROCMODE" = 'rebuild' ]; then
+if [ "$PROCMODE" = 'build' -o "$PROCMODE" = 'rebuild' ]; then
   parse_items -s $*
 else
   parse_items -p $*
@@ -328,38 +308,33 @@ h=$(( $secs / 3600 )); m=$(( ( $secs / 60) % 60 )); s=$(( $secs % 60 ))
 echo "Time:       ${h}h ${m}m ${s}s"
 echo "Processed:  $PROCTOTAL"
 
-if [ "$PROCMODE" = 'update' -a "$OPT_DRYRUN" = 'y' ]; then
-  sort -u -k 1,1 -o $SR_UPDATEFILE $SR_UPDATEFILE
-  cat $SR_UPDATEFILE
+if [ "$OPT_DRYRUN" = 'y' ]; then
+  OKLIST="$(echo -n $OKLIST | sed -e "s/ /\n  /g" -e 's/^ */  /' | sort -u)"
+  echo "Dry run OK: $(echo -n $OKLIST | wc -w)"
+  [ "$OPT_VERBOSE" = 'y' -a -n "$OKLIST" ] && echo "$OKLIST"
 else
-  if [ "$OPT_DRYRUN" = 'y' ]; then
-    OKLIST="$(echo -n $OKLIST | sed -e "s/ /\n  /g" -e 's/^ */  /' | sort -u)"
-    echo "Dry run OK: $(echo -n $OKLIST | wc -w)"
-    [ "$OPT_VERBOSE" = 'y' -a -n "$OKLIST" ] && echo "$OKLIST"
-  else
-    echo "Added:      $(grep ': Added'   $SR_CHANGELOG | wc -l)"
-    [ "$OPT_VERBOSE" = 'y' ] && \
-      grep ': Added'   $SR_CHANGELOG | sed -e 's/^/  /' -e 's/:.*//' | sort
-    echo "Updated:    $(grep ': Updated' $SR_CHANGELOG | wc -l)"
-    [ "$OPT_VERBOSE" = 'y' ] && \
-      grep ': Updated' $SR_CHANGELOG | sed -e 's/^/  /' -e 's/:.*//' | sort
-    echo "Rebuilt:    $(grep ': Rebuilt' $SR_CHANGELOG | wc -l)"
-    [ "$OPT_VERBOSE" = 'y' ] && \
-      grep ': Rebuilt' $SR_CHANGELOG | sed -e 's/^/  /' -e 's/:.*//' | sort
-    echo "Removed:    $(grep ': Removed' $SR_CHANGELOG | wc -l)"
-    [ "$OPT_VERBOSE" = 'y' ] && \
-      grep ': Removed' $SR_CHANGELOG | sed -e 's/^/  /' -e 's/:.*//' | sort
-  fi
-  SKIPPEDLIST="$(echo -n $SKIPPEDLIST | sed -e "s/ /\n  /g" -e 's/^ */  /' | sort -u)"
-  echo "Skipped:    $(echo -n $SKIPPEDLIST | wc -w)"
-  [ "$OPT_VERBOSE" = 'y' -a -n "$SKIPPEDLIST" ] && echo "$SKIPPEDLIST"
-  FAILEDLIST="$(echo -n $FAILEDLIST   | sed -e "s/ /\n  /g" -e 's/^ */  /' | sort -u)"
-  echo "Failed:     $(echo -n $FAILEDLIST | wc -w)"
-  [ "$OPT_VERBOSE" = 'y' -a -n "$FAILEDLIST" ] && echo "$FAILEDLIST"
-  ABORTEDLIST="$(echo -n $ABORTEDLIST | sed -e "s/ /\n  /g" -e 's/^ */  /' | sort -u)"
-  echo "Aborted:    $(echo -n $ABORTEDLIST | wc -w)"
-  [ "$OPT_VERBOSE" = 'y' -a -n "$ABORTEDLIST" ] && echo "$ABORTEDLIST"
+  echo "Added:      $(grep ': Added'   $SR_CHANGELOG | wc -l)"
+  [ "$OPT_VERBOSE" = 'y' ] && \
+    grep ': Added'   $SR_CHANGELOG | sed -e 's/^/  /' -e 's/:.*//' | sort
+  echo "Updated:    $(grep ': Updated' $SR_CHANGELOG | wc -l)"
+  [ "$OPT_VERBOSE" = 'y' ] && \
+    grep ': Updated' $SR_CHANGELOG | sed -e 's/^/  /' -e 's/:.*//' | sort
+  echo "Rebuilt:    $(grep ': Rebuilt' $SR_CHANGELOG | wc -l)"
+  [ "$OPT_VERBOSE" = 'y' ] && \
+    grep ': Rebuilt' $SR_CHANGELOG | sed -e 's/^/  /' -e 's/:.*//' | sort
+  echo "Removed:    $(grep ': Removed' $SR_CHANGELOG | wc -l)"
+  [ "$OPT_VERBOSE" = 'y' ] && \
+    grep ': Removed' $SR_CHANGELOG | sed -e 's/^/  /' -e 's/:.*//' | sort
 fi
+SKIPPEDLIST="$(echo -n $SKIPPEDLIST | sed -e "s/ /\n  /g" -e 's/^ */  /' | sort -u)"
+echo "Skipped:    $(echo -n $SKIPPEDLIST | wc -w)"
+[ "$OPT_VERBOSE" = 'y' -a -n "$SKIPPEDLIST" ] && echo "$SKIPPEDLIST"
+FAILEDLIST="$(echo -n $FAILEDLIST   | sed -e "s/ /\n  /g" -e 's/^ */  /' | sort -u)"
+echo "Failed:     $(echo -n $FAILEDLIST | wc -w)"
+[ "$OPT_VERBOSE" = 'y' -a -n "$FAILEDLIST" ] && echo "$FAILEDLIST"
+ABORTEDLIST="$(echo -n $ABORTEDLIST | sed -e "s/ /\n  /g" -e 's/^ */  /' | sort -u)"
+echo "Aborted:    $(echo -n $ABORTEDLIST | wc -w)"
+[ "$OPT_VERBOSE" = 'y' -a -n "$ABORTEDLIST" ] && echo "$ABORTEDLIST"
 WARNCOUNT=$(grep '^WARNING: ' $SR_LOGFILE | wc -l)
 echo "Warnings:   $WARNCOUNT"
 [ "$OPT_VERBOSE" = 'y' ] && grep '^WARNING: ' $SR_LOGFILE | sed 's/^WARNING: /  /'
@@ -396,9 +371,7 @@ fi
 
 #-------------------------------------------------------------------------------
 
-rm -f \
-  $SR_CHANGELOG \
-  $SR_UPDATEFILE
+rm -f $SR_CHANGELOG
 
 echo ""
 exit 0
