Mega rewrite

diff --git a/slackrepo b/slackrepo
--- a/slackrepo
+++ b/slackrepo
@@ -44,7 +44,7 @@ function print_usage
 
 function exit_cleanup
 {
-  rm -f $PIDFILE
+  rm -f "$PIDFILE"
 }
 
 #-------------------------------------------------------------------------------
@@ -115,14 +115,10 @@ done
 # Startup
 #-------------------------------------------------------------------------------
 
-# Use the standard Unix TMPDIR for things that SR_TMP wouldn't be good for
-# (SR_TMP gets cleaned during execution)
-TMPDIR=${TMPDIR:-/tmp}
-
 PIDFILE="/var/run/$(basename $0).pid"
-oldpid=$(cat $PIDFILE 2>/dev/null)
+oldpid=$(cat "$PIDFILE" 2>/dev/null)
 if [ -z "$oldpid" -o -z "$(pgrep -u root $(basename $0) | grep -v $$)" ]; then
-  echo $$ > $PIDFILE
+  echo $$ > "$PIDFILE"
 else
   echo "$(basename $0): Another instance is already running." >&2
   exit_cleanup
@@ -133,9 +129,9 @@ fi
 trap "exit_cleanup; exit 1" SIGINT SIGQUIT SIGTERM
 
 # Get the support functions
-for f in /usr/libexec/$(basename $0)/functions.d/*functions.sh; do
-  if [ -x $f ]; then
-    . $f
+for f in /usr/libexec/$(basename $0)/functions.d/*.sh; do
+  if [ -x "$f" ]; then
+    . "$f"
   fi
 done
 
@@ -149,12 +145,12 @@ SR_REPO="${SR_REPO:-$REPO}"
 [ -z "${SR_REPO:=$REPO}" ] && SR_REPO="SBo"
 
 # Set config variables from environment:
-varlist="SBREPO PKGREPO SRCREPO \
-         HINTS LOGDIR TMP \
-         ARCH TAG PKGTYPE NUMJOBS USE_GENREPOS \
-         INIT_GITCLONE INIT_GITBRANCH"
+varnames="SBREPO PKGREPO SRCREPO \
+          HINTS LOGDIR TMP \
+          ARCH TAG PKGTYPE NUMJOBS USE_GENREPOS \
+          INIT_GITCLONE INIT_GITBRANCH"
 # We'll prefix all these with SR_ to stop SlackBuilds picking them up
-for envvar in $varlist ; do
+for envvar in $varnames ; do
   myvar="SR_$envvar"
   eval $myvar="${!envvar}"
 done
@@ -170,16 +166,16 @@ if [ -f "$userconf" ]; then
   . "$userconf"
 fi
 # Backfill the SR_ variables from config and unset the config variables
-for confvar in $varlist ; do
+for confvar in $varnames ; do
   myvar="SR_$confvar"
   [ -z "${!myvar}" ] && eval $myvar=\"${!confvar}\"
   eval unset $confvar
 done
 
-# Do this now so we can log the config:
-mkdir -p $SR_LOGDIR
-MAINLOG=$SR_LOGDIR/$(basename $0)_$(date '+%F_%T').log
-> $MAINLOG
+# Do this early so we can log the config:
+mkdir -p "$SR_LOGDIR"
+MAINLOG="$SR_LOGDIR"/$(basename $0)_$(date '+%F_%T').log
+> "$MAINLOG"
 
 # If SR_NUMJOBS or SR_ARCH not set, work them out and set them explicitly
 if [ -z "$SR_NUMJOBS" ]; then
@@ -209,7 +205,7 @@ log_verbose "  --$PROCMODE"
 [ "$OPT_DRYRUN" = 'y'  ] && log_verbose "  --dry-run"
 [ "$OPT_TEST" = 'y'    ] && log_verbose "  --test"
 [ "$OPT_KEEPTMP" = 'y' ] && log_verbose "  --keep-tmp"
-for var in $varlist; do
+for var in $varnames; do
   myvar="SR_$var"
   log_verbose "  $var='${!myvar}'"
 done
@@ -219,23 +215,10 @@ done
 # Initialisation
 #-------------------------------------------------------------------------------
 
-# Associative arrays to store stuff from .info files:
-declare -A INFOVERSION INFOREQUIRES INFODOWNLIST INFOMD5LIST
-# and to store dependency, revision and other stuff:
-declare -A SRCDIR GITREV GITDIRTY DEPCACHE REVCACHE
-# and for each type of hint:
-declare -A HINT_skipme HINT_md5ignore HINT_makej1 HINT_no_uninstall
-declare -A HINT_cleanup HINT_uidgid HINT_answers
-declare -A HINT_options HINT_optdeps HINT_readmedeps HINT_version
+# Arrays for tracking build outcomes:
+declare -a OKLIST SKIPPEDLIST FAILEDLIST ABORTEDLIST
 
-TMP_CHANGELOG="$TMPDIR/sr_changelog_${SR_REPO}.tmp"
-if [ -s "$TMP_CHANGELOG" ]; then
-  log_normal "Continuing changelog $TMP_CHANGELOG from previous run."
-else
-  > $TMP_CHANGELOG
-fi
-
-# Temporary directories and files
+# Temporary directory:
 SR_TMP=${SR_TMP:-/tmp/SBo}
 # really really don't want the next bit to go badly ;-)
 if [ -n "$SR_TMP" -a -d "$SR_TMP" -a "$OPT_KEEPTMP" != 'y' ]; then
@@ -243,6 +226,25 @@ if [ -n "$SR_TMP" -a -d "$SR_TMP" -a "$OPT_KEEPTMP" != 'y' ]; then
   rm -rf "${SR_TMP:-dont-tase-me-bro}"/*
 else
   mkdir -p $SR_TMP
+fi
+
+# Use the standard Unix TMPDIR for things that SR_TMP wouldn't be good for
+# (SR_TMP gets cleaned during execution)
+TMPDIR=${TMPDIR:-/tmp}
+
+# Changelog:
+TMP_CHANGELOG="$TMPDIR"/sr_changelog_"$SR_REPO".tmp
+if [ -s "$TMP_CHANGELOG" ]; then
+  log_normal "Continuing changelog $TMP_CHANGELOG from previous run."
+else
+  > "$TMP_CHANGELOG"
+fi
+
+# Disposable package repository for dry run:
+if [ "$OPT_DRYRUN" = 'y' ]; then
+  DRYREPO="$SR_TMP"/sr_DRY.$$
+  rm -rf "$DRYREPO"
+  mkdir -p "$DRYREPO"
 fi
 
 # Create directories:
@@ -271,14 +273,14 @@ elif [ -d $SR_SBREPO/.git ]; then
   muck="$(git status -s .)"
   branch=$(git rev-parse --abbrev-ref HEAD)
   if [ -z "$muck" -a "$branch" = "$SLACKVER" ]; then
-    if [ -n "$(find $SR_SBREPO/.git/FETCH_HEAD -mtime +1 2>/dev/null)" ]; then
+    if [ -n "$(find "$SR_SBREPO"/.git/FETCH_HEAD -mtime +1 2>/dev/null)" ]; then
       log_normal "Updating git ..."
       if [ "$OPT_QUIET" = 'y' ]; then
-        git fetch -a                       >> $MAINLOG 2>&1
-        git merge --ff-only origin/$branch >> $MAINLOG 2>&1
+        git fetch -a                         >> "$MAINLOG" 2>&1
+        git merge --ff-only origin/"$branch" >> "$MAINLOG" 2>&1
       else
-        git fetch -a                       2>&1 | tee -a $MAINLOG
-        git merge --ff-only origin/$branch 2>&1 | tee -a $MAINLOG
+        git fetch -a                         2>&1 | tee -a "$MAINLOG"
+        git merge --ff-only origin/"$branch" 2>&1 | tee -a "$MAINLOG"
       fi
       log_normal "Finished updating git."
     fi
@@ -287,7 +289,7 @@ fi
 
 # git: log a summary
 GOTGIT='n'
-if [ -d $SR_SBREPO/.git ]; then
+if [ -d "$SR_SBREPO"/.git ]; then
   GOTGIT='y'
   [ "$OPT_VERBOSE" = 'y' ] && echo ""
   log_verbose "Git repo:   $SR_SBREPO"
@@ -302,7 +304,7 @@ fi
 
 # Warn about already installed packages (using package tag)
 if [ -n "$SR_TAG" ]; then
-  installed=$(ls /var/log/packages/*$SR_TAG 2>/dev/null)
+  installed=$(ls /var/log/packages/*"$SR_TAG" 2>/dev/null)
   if [ -n "$installed" ]; then
     for pkg in $installed; do
       # don't moan if it has a no_uninstall hint
@@ -314,15 +316,7 @@ if [ -n "$SR_TAG" ]; then
   fi
 fi
 
-#-------------------------------------------------------------------------------
-# Main loop
-#-------------------------------------------------------------------------------
-
-OKLIST=''
-SKIPPEDLIST=''
-FAILEDLIST=''
-ABORTEDLIST=''
-
+# Command arguments:
 if [ $# = 0 ]; then
   if [ "$PROCMODE" = 'remove' ]; then
     # remove mode with no args => do nothing
@@ -332,35 +326,54 @@ if [ $# = 0 ]; then
     exit 3
   elif [ "$PROCMODE" = 'update' ]; then
     # update mode with no args => process everything in the package repo
-    set -- $(cd $SR_PKGREPO; find * -maxdepth 0 -type d 2>/dev/null)
+    set -- "$SR_PKGREPO"
   else
-    # other modes with no args => process everything in the git repo
-    set -- $(cd $SR_SBREPO; find * -maxdepth 0 -type d 2>/dev/null)
+    # other modes with no args => process everything in the SlackBuilds repo
+    set -- "$SR_SBREPO"
   fi
 fi
 
+#-------------------------------------------------------------------------------
+# Main loop
+#-------------------------------------------------------------------------------
+
 BLAME="$(basename $0)"
-if [ "$PROCMODE" = 'build' -o "$PROCMODE" = 'rebuild' ]; then
-  parse_items -s $*
-else
-  parse_items -p $*
-fi
-# ignore status - we'll just process the items that were ok
-unset BLAME
-
-if [ "$OPT_DRYRUN" = 'y' ]; then
-  DRYREPO=$SR_TMP/sr_DRY.$$
-  rm -rf $DRYREPO
-  mkdir -p $DRYREPO
-fi
-
-PROCTOTAL=0
-for ITEMPATH in $ITEMLIST; do
-  PROCTOTAL=$(( $PROCTOTAL + 1 ))
-  process_item $ITEMPATH
+while [ $# != 0 ]; do
+  item="$1"
+  shift
+  if [ "$PROCMODE" = 'build' -o "$PROCMODE" = 'rebuild' ]; then
+    parse_items -s "$item"
+  else # 'update' or 'remove'
+    parse_items -p "$item"
+  fi
+  # Note that we set the variable $ITEMID (upper case) so that other functions
+  # called recursively (which get $itemid as an argument) can test whether they
+  # are dealing with the top level item.
+  for ITEMID in "${ITEMLIST[@]}"; do
+    echo ""
+    log_start "$ITEMID"
+    case "$PROCMODE" in
+    'build' | 'rebuild' )
+      build_with_deps "$ITEMID"
+      ;;
+    'update' )
+      itemdir="${ITEMDIR[$ITEMID]}"
+      if [ -d "$SR_SBREPO"/"$itemdir"/ ]; then
+        build_with_deps "$ITEMID"
+      else
+        remove_item "$ITEMID"
+      fi
+      ;;
+    'remove' )
+      remove_item "$ITEMID"
+      ;;
+    *)
+      log_error "$(basename $0): Unrecognised PROCMODE = $PROCMODE"
+      exit 4
+      ;;
+    esac
+  done
 done
-
-[ "$OPT_KEEPTMP" != 'y' ] && rm -rf $DRYREPO
 
 #-------------------------------------------------------------------------------
 # Print a summary of what happened
@@ -374,56 +387,60 @@ echo ""
 secs=$(( $(date +%s) - $starttime ))
 h=$(( $secs / 3600 )); m=$(( ( $secs / 60) % 60 )); s=$(( $secs % 60 ))
 echo "Time:       ${h}h ${m}m ${s}s"
-echo "Processed:  $PROCTOTAL"
+echo "Processed:  $(( ${#OKLIST[@]} + ${#SKIPPEDLIST[@]} + ${#FAILEDLIST[@]} + ${#ABORTEDLIST[@]} ))"
 
 if [ "$OPT_DRYRUN" = 'y' ]; then
-  OKLIST="$(echo -n $OKLIST | sed -e "s/ /\n  /g" -e 's/^ */  /' | sort -u)"
-  echo "Dry run OK: $(echo -n $OKLIST | wc -w)"
-  [ "$OPT_QUIET" != 'y' -a -n "$OKLIST" ] && echo "$OKLIST"
+  OKLIST=( $(printf '%s\n' "${OKLIST[@]}" | sort -u) )
+  okcount="${#OKLIST[@]}"
+  echo "Dry run OK: $okcount"
+  [ "$OPT_QUIET" != 'y' -a "$okcount" != 0 ] && printf '  %s\n' "${OKLIST[@]}"
 else
-  echo "Added:      $(grep ': Added'   $TMP_CHANGELOG | wc -l)"
+  echo "Added:      $(grep ': Added'   "$TMP_CHANGELOG" | wc -l)"
   [ "$OPT_QUIET" != 'y' ] && \
-    grep ': Added'   $TMP_CHANGELOG | sed -e 's/^/  /' -e 's/:.*//' | sort
-  echo "Updated:    $(grep ': Updated' $TMP_CHANGELOG | wc -l)"
+    grep ': Added'   "$TMP_CHANGELOG" | sed -e 's/^/  /' -e 's/:.*//' | sort
+  echo "Updated:    $(grep ': Updated' "$TMP_CHANGELOG" | wc -l)"
   [ "$OPT_QUIET" != 'y' ] && \
-    grep ': Updated' $TMP_CHANGELOG | sed -e 's/^/  /' -e 's/:.*//' | sort
-  echo "Rebuilt:    $(grep ': Rebuilt' $TMP_CHANGELOG | wc -l)"
+    grep ': Updated' "$TMP_CHANGELOG" | sed -e 's/^/  /' -e 's/:.*//' | sort
+  echo "Rebuilt:    $(grep ': Rebuilt' "$TMP_CHANGELOG" | wc -l)"
   [ "$OPT_QUIET" != 'y' ] && \
-    grep ': Rebuilt' $TMP_CHANGELOG | sed -e 's/^/  /' -e 's/:.*//' | sort
-  echo "Removed:    $(grep ': Removed' $TMP_CHANGELOG | wc -l)"
+    grep ': Rebuilt' "$TMP_CHANGELOG" | sed -e 's/^/  /' -e 's/:.*//' | sort
+  echo "Removed:    $(grep ': Removed' "$TMP_CHANGELOG" | wc -l)"
   [ "$OPT_QUIET" != 'y' ] && \
-    grep ': Removed' $TMP_CHANGELOG | sed -e 's/^/  /' -e 's/:.*//' | sort
+    grep ': Removed' "$TMP_CHANGELOG" | sed -e 's/^/  /' -e 's/:.*//' | sort
 fi
-SKIPPEDLIST="$(echo -n $SKIPPEDLIST | sed -e "s/ /\n  /g" -e 's/^ */  /' | sort -u)"
-echo "Skipped:    $(echo -n $SKIPPEDLIST | wc -w)"
-[ "$OPT_QUIET" != 'y' -a -n "$SKIPPEDLIST" ] && echo "$SKIPPEDLIST"
-FAILEDLIST="$(echo -n $FAILEDLIST   | sed -e "s/ /\n  /g" -e 's/^ */  /' | sort -u)"
-echo "Failed:     $(echo -n $FAILEDLIST | wc -w)"
-[ "$OPT_QUIET" != 'y' -a -n "$FAILEDLIST" ]  && echo "$FAILEDLIST"
-ABORTEDLIST="$(echo -n $ABORTEDLIST | sed -e "s/ /\n  /g" -e 's/^ */  /' | sort -u)"
-echo "Aborted:    $(echo -n $ABORTEDLIST | wc -w)"
-[ "$OPT_QUIET" != 'y' -a -n "$ABORTEDLIST" ] && echo "$ABORTEDLIST"
-WARNCOUNT=$(grep '^WARNING: ' $MAINLOG | wc -l)
-echo "Warnings:   $WARNCOUNT"
-[ "$OPT_QUIET" != 'y' ] && grep '^WARNING: ' $MAINLOG | sed 's/^WARNING: /  /'
+SKIPPEDLIST=( $(printf '%s\n' "${SKIPPEDLIST[@]}" | sort -u) )
+skippedcount="${#SKIPPEDLIST[@]}"
+echo "Skipped:    $skippedcount"
+[ "$OPT_QUIET" != 'y' -a "$skippedcount" != 0 ] && printf '  %s\n' "${SKIPPEDLIST[@]}"
+FAILEDLIST=( $(printf '%s\n' "${FAILEDLIST[@]}" | sort -u) )
+failedcount="${#FAILEDLIST[@]}"
+echo "Failed:     $failedcount"
+[ "$OPT_QUIET" != 'y' -a "$failedcount" != 0 ]  && printf '  %s\n' "${FAILEDLIST[@]}"
+ABORTEDLIST=( $(printf '%s\n' "${ABORTEDLIST[@]}" | sort -u) )
+abortedcount="${#ABORTEDLIST[@]}"
+echo "Aborted:    $abortedcount"
+[ "$OPT_QUIET" != 'y' -a "$abortedcount" != 0 ] && printf '  %s\n' "${ABORTEDLIST[@]}"
+warncount=$(grep '^WARNING: ' "$MAINLOG" | wc -l)
+echo "Warnings:   $warncount"
+[ "$OPT_QUIET" != 'y' ] && grep '^WARNING: ' "$MAINLOG" | sed 's/^WARNING: /  /'
 
 #-------------------------------------------------------------------------------
 # Package repository maintenance: gen_repos_files.sh
 #-------------------------------------------------------------------------------
 
 genrepstat=0
-if [ "$OPT_DRYRUN" != 'y' -a -s $TMP_CHANGELOG ]; then
+if [ "$OPT_DRYRUN" != 'y' -a -s "$TMP_CHANGELOG" ]; then
   rcfile=~/.genreprc
-  [ -f $rcfile ] && { set -e; . $rcfile; set +e; }
+  [ -f "$rcfile" ] && { set -e; . "$rcfile"; set +e; }
   if [ "$SR_USE_GENREPOS" = 1 ]; then
     echo ""
     log_start "gen_repos_files.sh"
     # 'man sort' says an in-place sort is ok, so let's be lazy :-)
-    sort -o $TMP_CHANGELOG $TMP_CHANGELOG
+    sort -o "$TMP_CHANGELOG" "$TMP_CHANGELOG"
     if [ "$RSS_UUID" = '' ]; then
       setrssuuid="RSS_UUID=\"$(uuidgen -t)\""
       log_normal "Note: setting $setrssuuid in $rcfile"
-      echo "$setrssuuid" >> $rcfile
+      echo "$setrssuuid" >> "$rcfile"
       eval $setrssuuid
     fi
     REPOSROOT="$REPOSROOT" REPOSOWNER="$REPOSOWNER" REPOSOWNERGPG="$REPOSOWNERGPG" DL_URL="$DL_URL" \
@@ -431,17 +448,20 @@ if [ "$OPT_DRYRUN" != 'y' -a -s $TMP_CHANGELOG ]; then
     RSS_DESCRIPTION="$RSS_DESCRIPTION" RSS_FEEDMAX="$RSS_FEEDMAX" RSS_UUID="$RSS_UUID" \
     GPGBIN="$GPGBIN" USE_GPGAGENT="$USE_GPGAGENT" FOR_SLAPTGET="$FOR_SLAPTGET" \
     FOLLOW_SYMLINKS="$FOLLOW_SYMLINKS" REPO_SUBDIRS="$REPO_SUBDIRS" \
-    sh /usr/libexec/$(basename $0)/gen_repos_files.sh -l $TMP_CHANGELOG | tee -a $MAINLOG
+    sh /usr/libexec/$(basename $0)/gen_repos_files.sh -l "$TMP_CHANGELOG" | tee -a "$MAINLOG"
     genrepstat=$?
-    [ $genrepstat != 0 ] && log_error "gen_repos_files.sh failed -- changelog retained"
+    [ "$genrepstat" != 0 ] && log_error "gen_repos_files.sh failed -- changelog retained"
     echo ""
     log_important "Finished gen_repos_files.sh at $(date +%T)"
   fi
 fi
-[ $genrepstat = 0 -a "$OPT_KEEPTMP" != 'y' ] && rm -f $TMP_CHANGELOG
 
 #-------------------------------------------------------------------------------
 
 echo ""
+
+[ "$genrepstat" = 0 -a "$OPT_KEEPTMP" != 'y' ] && rm -f "$TMP_CHANGELOG"
+[ "$OPT_KEEPTMP" != 'y' ] && rm -rf "$DRYREPO"
 exit_cleanup
+
 exit 0
